name: 'loki-sync-jira-to-github'
description: 'Synchronize Jira issues to GitHub repositories'
inputs:
  from-jira:
    description: 'Flag to indicate from Jira'
    required: true
  to-repo:
    description: 'The destination repository'
    required: true
runs:
  using: 'docker'
  image: 'quay.io/aurora-labs-42/loki-action:latest'
  args:
    - ${{ inputs.from-jira }}
    - ${{ inputs.to-repo }}
